
/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package PalindromeP;
import java.util.Scanner;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        
//        Scanner input = new Scanner(System.in);
//        System.out.println("Welcome To Palindrome Checker");
//        System.out.println("Enter Palindrome Numbers");
//        String inp = input.nextLine();

 Scanner input = new Scanner(System.in);
	     System.out.println("Welcome To Palindrome Checker");
	     System.out.println("Enter Palindrome Numbers: ");
	     int inp1;
	     
	     inp1 = input.nextInt();
	     
	     int inp2 = inp1;
	     int inp3 = 0;
	     
	     while(inp1!=0) {
	    	 inp3 = inp3*10 + inp1 %10;
	    	 inp1 = inp1/10;
	     }
	     if(inp2 == inp3) {
	    	 System.out.println(inp3 + " Palindrome Number");
	     }
	     else {
	    	 System.out.println(inp3 + " Not Palindrome Number");
	     }
	    
    }
}
